### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [50]:
import numpy as np

a = np.linspace(12, 24, 12, endpoint=False)
print(a)

[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]


### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [51]:
rea1 = a.reshape(2, 6)
print('Форма 1:\n', rea1)
print()

rea2 = a.reshape(3, 4)
print('Форма 2:\n', rea2)
print()

rea3 = a.reshape(4, 3)
print('Форма 3:\n', rea3)
print()

rea4 = a.reshape(6, 2)
print('Форма 4:\n', rea4)
print()

rea5 = a.reshape(12, 1)
print('Форма 5:\n', rea5)
print()

Форма 1:
 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

Форма 2:
 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]

Форма 3:
 [[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]

Форма 4:
 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]

Форма 5:
 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]



### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [52]:
rea1 = a.reshape(-1, 6)
print('Форма 1`:\n', rea1)
print()

rea2 = a.reshape(-1, 4)
print('Форма 2`:\n', rea2)
print()

rea3 = a.reshape(1, -1)
print('Форма 3`:\n', rea3)
print()

rea4 = a.reshape(6, -1)
print('Форма 4`:\n', rea4)
print()

rea5 = a.reshape(12, -1)
print('Форма 5`:\n', rea5)

Форма 1`:
 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]

Форма 2`:
 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]

Форма 3`:
 [[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]]

Форма 4`:
 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]

Форма 5`:
 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [ ]:
Нет - каждая строка является элементом второго измерения.
А вот массив из одной строки и любого количества элементов являются одномерным, 
т.к. строки являются начальным измерение(dimension), а все последующие дополнительными

### Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.  
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [98]:
norma = np.random.randn(3, 4)
print(f'norma size: {norma.size} \nelements:\n{norma}')
print()

flat_norma = norma.flatten()
print(f'flat_norma size {flat_norma.size} \nelements:\n{flat_norma}')

norma size: 12 
elements:
[[-0.11543683 -0.23313823  1.16797116  0.5300698 ]
 [ 0.64980503  1.00176818  1.49244005 -2.4771216 ]
 [ 0.02489491  0.91730676  0.14216859  0.60893798]]

flat_norma size 12
elements:
[-0.11543683 -0.23313823  1.16797116  0.5300698   0.64980503  1.00176818
  1.49244005 -2.4771216   0.02489491  0.91730676  0.14216859  0.60893798]


### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [63]:
arr_a =  np.arange(20, 0, -2)
print(arr_a)

[20 18 16 14 12 10  8  6  4  2]


### Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.  
В чем разница между массивами a и b?

In [64]:
arr_b = np.arange(20, 1, -2).reshape(10, 1)
print(arr_b)

# Возможно я не понял вопроса, но мне кажется что ответ в размерности

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [93]:
zero_a = np.zeros((2,2))
print(f'zero_a:\n{zero_a}')
print()

one_b = np.ones((3, 2))
print(f'one_b:\n{one_b}')

# c = np.concatenate((zero_a, one_b), axis=0) 
v = np.vstack((zero_a, one_b))
print(f'size {v.size} v:\n{v}')

zero_a:
[[0. 0.]
 [0. 0.]]

one_b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
size 10 v:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.  
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.  
Получить матрицу At путем транспонирования матрицы A.  
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.  
Какой размер имеет матрица B?  
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [161]:
arr_a = np.linspace(0, 12, 12, dtype=int)

A = arr_a.reshape(4, 3)
print(f'Размер матрицы A:{A.shape} элементы:\n{A}')
print()

Alt = A.T
print(f'Размер матрицы Alt:{Alt.shape} элементы:\n{Alt}')
print()

B = np.matmul(A, Alt)
print(f'Размер матрицы B:{B.shape} элементы:\n{B}')
print()

B_inv = np.linalg.inv(D)
print(f'Размер матрицы B_inv:{B_inv.shape} элементы:\n{B_inv}')
print()

B_det = np.linalg.det(B)
print(f'Для матрицы B возможно вычислить обратную матрицу inv_B так как детерминант(определитель) матрицы B равен {B_det}')

Размер матрицы A:(4, 3) элементы:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 12]]

Размер матрицы Alt:(3, 4) элементы:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 12]]

Размер матрицы B:(4, 4) элементы:
[[  5  14  23  34]
 [ 14  50  86 127]
 [ 23  86 149 220]
 [ 34 127 220 325]]

Размер матрицы B_inv:(4, 4) элементы:
[[-0.03074951  0.01931829  0.01185118 -0.00756704]
 [ 0.02587782 -0.0068445  -0.00769831  0.00046424]
 [-0.02142921  0.01595747  0.00028242  0.00078824]
 [ 0.00943355 -0.01241482  0.00136303  0.0030226 ]]

Для матрицы B возможно вычислить обратную матрицу inv_B так как детерминант(определитель) матрицы B равен 0.0


### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [123]:
np.random.seed(42)

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [140]:
arr = np.random.randint(0, 16, size=16)
print(arr)

[ 7 13  6 11  8 13  7  4 15 12  1 14  4  7  9  8]


### Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C.  
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.  
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [170]:
C = arr.reshape(4, 4)
D = C*10 + B
print(f'Размер матрицы D:{D.shape} элементы:\n{D}')
print()


D_det = np.linalg.det(D)
D_inv = np.linalg.inv(D)
D_rank = np.linalg.matrix_rank(B)

print(f'Детерминант матрицы D = {D_det}\n' +
      f'Ранг матрицы D = {D_rank}\n' +
      f'Матрицы обратная матрице D состоит из элементов:\n {D_inv}')


Размер матрицы D:(4, 4) элементы:
[[ 75 144  83 144]
 [ 94 180 156 167]
 [173 206 159 360]
 [ 74 197 310 405]]

Детерминант матрицы D = 163084889.99999997
Ранг матрицы D = 3
Матрицы обратная матрице D состоит из элементов:
 [[-0.03074951  0.01931829  0.01185118 -0.00756704]
 [ 0.02587782 -0.0068445  -0.00769831  0.00046424]
 [-0.02142921  0.01595747  0.00028242  0.00078824]
 [ 0.00943355 -0.01241482  0.00136303  0.0030226 ]]


### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.  
Убедитесь, что в матрице D_inv остались только нули и единицы.  
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [183]:
D_inv1 = np.where(D_inv > 0)
D_inv[D_inv1] = 1

D_inv1 = np.where(D_inv < 0)
D_inv[D_inv1] = 0
print(f'Элементы матрицы D_inv:\n{D_inv}')
print()

E = np.where(D_inv, B, C)
print(f'Элементы матрицы B:\n{B}')
print()

print(f'Элементы матрицы C:\n{C}')
print()

print(f'Элементы матрицы E:\n{E}')
print()



Элементы матрицы D_inv:
[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 1.]
 [1. 0. 1. 1.]]

Элементы матрицы B:
[[  5  14  23  34]
 [ 14  50  86 127]
 [ 23  86 149 220]
 [ 34 127 220 325]]

Элементы матрицы C:
[[ 7 13  6 11]
 [ 8 13  7  4]
 [15 12  1 14]
 [ 4  7  9  8]]

Элементы матрицы E:
[[  7  14  23  11]
 [ 14  13   7 127]
 [ 15  86 149 220]
 [ 34   7 220 325]]

